# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      ./kernel.nix
      ./kernel-extra.nix
    
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" "vfio-pci" ];
  boot.kernelModules = [ "kvm-amd" ]
  boot.extraModulePackages = [ ];
  

 
  services.fstrim.enable = true;


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cb936604-d662-415e-b571-90302dc9943d";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/cb936604-d662-415e-b571-90302dc9943d";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/80C7-BEDE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/157a84a5-3f20-4d63-8254-e6594cd139ce"; }
    ];




  
   # Enable networking
#  networking.networkmanager.enable = true;
#  networking.hostName = "udimension-genesis-nixos"; # Define your hostname.

  networking = {
    networkmanager.enable = true;
    hostName = "udimension-kirigiri"; # Define your hostname.
    interfaces.wlp10s0 = {
      ipv4.addresses = [{
        address = "192.168.1.5";
        prefixLength = 24;
      }];



    };

  };


  
  # Disable NetworkManager's internal DNS resolution
#  networking.networkmanager.dns = "none";

  # These options are unnecessary when managing DNS ourselves
#  networking.useDHCP = false;
#  networking.dhcpcd.enable = false;

  # Configure DNS servers manually (this example uses Cloudflare and Google DNS)
  # IPv6 DNS servers can be used here as well.
#  networking.nameservers = [
#    "1.1.1.1"
#    "1.0.0.1"
#    "8.8.8.8"
#    "8.8.4.4"
#  ];


  networking.useDHCP = lib.mkDefault true;
  
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  
}
