# keybinds related to workspaces are still in keybinds.conf



# monitor sets
workspace = 1, monitor:DP-3
workspace = 2, monitor:DP-3
workspace = 3, monitor:DP-3
workspace = 4, monitor:DP-3
workspace = 5, monitor:DP-3
workspace = 6, monitor:DP-2
workspace = 7, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 9, monitor:DP-2
workspace = 10, monitor:DP-2

# special workspace thingies
workspace = special:Bluetooth, on-created-empty:[float] blueman-manager
workspace = special:Terminal, on-created-empty:[float] kitty
